### ISSUE TITLE
MultiMatcher e TaggedMatch

### ISSUE THREAD

**Issue by EPresident** [EPresident/UniUdBig#10]
Per implementare il matching multiplo era stato detto di usare come return value una lista di coppie (Match,Redex/Guest); tuttavia, leggendo il Javadoc di Match, mi sono reso conto che c'è un metodo pubblico Match.getRedex(): può essere che sia sufficiente questo ad identificare da che guest viene il match?

**Comment by lucageatti** [comment]
Sì, penso sia sufficiente. A meno che tu, nella lista del metodo "match()" di "MultiMatcher", non abbia due redex uguali (che non avrebbe senso), il metodo Match.getRedex() identifica univocamente il guest al quale fa riferimento il match.

**Comment by lucageatti** [comment]
PS: non mi ricordo a cosa serviva il MultiMatcher. Era forse per fare il matching pesato o il random walk?

**Comment by EPresident** [comment]
Il MultiMatcher era per fare il match di un host con più guest in una sola operazione. Allora evito di creare classi inutili e provo ad utilizzare le API di Match.
