### ISSUE TITLE
RandomSim

### ISSUE THREAD

**Issue by lucageatti** [EPresident/UniUdBig#11]
Nella classe "RandomSim" non capisco il metodo "step()". Praticamente lo scopo è fare una BFS e, tra tutti gli stati adiacenti a quello corrente, sceglierne uno a caso. Però le righe 60 e 61 non mi tornano.

**Comment by lucageatti** [comment]
Ah ok capito: il nodo scelto a caso lo metti in cima alla coda, pur mantenendo tutti gli altri nodi di seguito.

**Comment by EPresident** [comment]
Esatto, è un modo per fare una scelta casuale pur tenendo conto dei percorsi che rimangono da esplorare, altrimenti si rischia di andare avanti all'infinito. Infatti c'era anche un TrueRandom che prendeva a caso senza criteri, ma non l'ho mai usato e forse neanche finito di implementare.
