### ISSUE TITLE
RR_Die1m causa un loop infinito nel BRS.

### ISSUE THREAD

**Issue by EPresident** [EPresident/UniUdBig#13]
Simulando il GoL 3x3 si cade in un loop infinito quando si cerca di applicare la regola [RR_Die1m](https://github.com/EPresident/UniUdBig/blob/GoL_Development/src/big/examples/life/RR_Die1m.java), cioè quella che prevede la morte di una cellula con uno o meno vicini in vita. Le cause sono tuttora sconosciute. La regola [RR_Die4p](https://github.com/EPresident/UniUdBig/blob/GoL_Development/src/big/examples/life/RR_Die4p.java), che prevede la morte con 4 o più vicini vivi, è molto simile anche nel codice ma non causa cicli infiniti.

**Comment by EPresident** [comment]
Si fa riferimento al branch GoL_Development.

**Comment by lucageatti** [comment]
Il malessere. Non ne ho idea, continuo a cercare. Il fatto è che è praticamente uguale a RR_Die4p

**Comment by EPresident** [comment]
Infatti. Non perderci troppo tempo! Farò presente martedì.

**Comment by EPresident** [comment]
A quanto pare in realtà non è un loop infinito, ma un'esplosione di match molto superiore alle possibilità di calcolo del computer.
