### ISSUE TITLE
graph size

### ISSUE THREAD

**Issue by lucageatti** [EPresident/UniUdBig#15]
Il metodo getGraphSize() della classe BigStateGraph non mi ritorna più il numero di nodi giusto. C'è qualche errore?

**Comment by lucageatti** [comment]
Che siano le righe da 117 a 120 nella classe BigStateGraph? Aggiungono un link tra due nodi anche se non sono isomorfi?

**Comment by EPresident** [comment]
No, quello è giusto: se non sono isomorfi, devi aggiungere il nodo al grafo. Ho dimenticato di aggiornare getGraphSize(): il metodo ritorna il numero di bucket, non di nodi. Provvedo subito.
