### ISSUE TITLE
Riassunto

### ISSUE THREAD

**Issue by lucageatti** [EPresident/UniUdBig#6]
1) Adesso la classe Sim oltre ad offrire il metodo stepAndGet() offre anche la possibilità di creare il grafo degli stati. E' una buona idea? Bisognerebbe creare una classe a parte?

2) Ho cambiato degli scope, come quello di BSGLink, da protected a public. Ci sono delle soluzioni migliori?

3) Nel package mc ho inserito il Model Checker, che prende in input il grafo degli stati e un tipo di visita (non strategia) per visitarlo.
Ho voluto differenziare il concetto di visita da quello di strategia perchè il primo descrive come visitare il grafo degli stati DOPO che è stato creato, il secondo descrive il metodo per crearlo. Secondo te?

4) Si può considerare, per motivi di efficienza, di creare una strategia DFS e di passargli delle proprietà così da costruire il grafo degli stati secondo la logica di DFS con il vantaggio di potersi fermare al primo nodo/stato che soddisfa la proprietà. Ci ho pensato e secondo me è meglio tenere separate le cose.
Secondo te?

**Comment by EPresident** [comment]
1. Lo stepAndGet è nato come metodo di debug, che ritorna i nodi aggiunti al grafo in modo da capire se tutto va come atteso, quindi in teoria non dovrebbe essere visibile nella versione finale;
2. Alla fin fine se BSGNode è pubblico ha senso che anche BSGLink lo sia;
3. Sono d'accordo che in teoria strategie e visite sono cose diverse, però secondo me si può accorpare il codice in una sola classe;
4. La DFS è il tipo di visita ottimale per controllare condizioni esistenziali, quindi è opportuno che venga implementata in qualche modo.
