### ISSUE TITLE
areMatchable()

### ISSUE THREAD

**Issue by lucageatti** [EPresident/UniUdBig#9]
Il metodo "areMatchable()" è protetto nella classe Matcher. Dato che lo devo usare all'interno della classe "Isomorph" ho creato una classe OpenMatcher un po inutile: rende pubblico il metodo "areMatchable()".
Il problema è questo: a noi ci serve la classe PropertyMatcher da noi creata. Essa estende la classe Matcher, che però ha il metodo "areMatchable()" protetto. Come fare senza la classe OpenMatcher?

**Comment by EPresident** [comment]
A meno di sfruttare in modo indiretto qualche metodo pubblico ( sembra ci sia solo match() ) non vedo altra soluzione che esporre areMatchable().
Tuttavia, leggendo il codice di PropertyMatcher.areMatchable() ho notato che non ci sono riferimenti né alla classe né alla superclasse: non puoi mettere areMatchable() direttamente dove ti serve, in Isomorphism?
